### ISSUE TITLE
Exports

### ISSUE THREAD

**Issue by TrEzEater** [renzuzu/renzu_spawn#1]
Hi there, 

I've tried the exports written in the README file from esx_multicharacter and it doesn't seem to work. You're fxmanifest file doesn't seem to have any exports either.

I'm sorry if I'm mistaken as I'm not that in tune with scripts at this moment in time, but if you could either point me into the right direction or fix the issue (if there is one in the first place), I would be very grateful.

Please view the attached;

![image](https://user-images.githubusercontent.com/77107481/206289066-3043014d-bdfb-4507-9185-189df0251e57.png)

![image](https://user-images.githubusercontent.com/77107481/206289309-343f778b-de6a-4442-abdf-1ae692fc29f6.png)

Sincerely, TrEzEater

**Comment by renzuzu** [comment]
did you start the spawn resource before multicharacter?

if player loads the esx multicharacter first, the export will be invalid or not found

or this can happen if spawn resource throwing error before you could load them

**Comment by TrEzEater** [comment]
> 
Hiya,

I've tried ensuring it in the server.cfg both before and after esx_multicharacter and it made no difference.

Thank you for the quick response

**Comment by renzuzu** [comment]
thats weird, 

then your last option is.

create a standalone folder

like [Multi] in /resources/[Multi]

drop the esx multicharacter there and spawn

then do the same ensure pattern

anything else there could be an error while loading the client side of spawn..

**Comment by renzuzu** [comment]
re open if issue still exist
