### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by ajmedina** [renzuzu/renzu_spawn#12]
I have a zombie server and I have renzu multichar and rspawn but I removed it because players use it as a teleport.

Is it possible to insert an option to SHOW ONLY THE renzu spawn at the first character creation login?

To prevent players from teleporting to other zones.

I have three secure zones on the server. I like that players choose one of the three to make a base.

**Comment by renzuzu** [comment]
havent able to test this yet.. but this should do the trick.

Spawn select will work only if its newly created

**Comment by ajmedina** [comment]
I look you have changed code in to your multicharacter 
i test that new versión with the changes. 
Only if is new !
Thanks big boy!!!

**Comment by ajmedina** [comment]
Tested   WORK PERFECT
