### ISSUE TITLE
Custom Location Exports

### ISSUE THREAD

**Issue by PB-Developent** [renzuzu/renzu_spawn#2]
The problem I have, is that I add exports to show player's houses, but then if you logout and back in to a different character, the previously added locations are there.

It seems the js or something is not removing locations like it should?

**Comment by renzuzu** [comment]
no you should retriggered the exports, when other player is logon.

every export from spawn should be unique

**Comment by PB-Developent** [comment]
I have tried it just like your instrutions.

Houses load into the menu, but when I log out of that character and select a new one, it still shows the old houses and any new ones for this next character

**Comment by PB-Developent** [comment]
When I debug the script, the correct data is being retrieved from the server, but it seems as if its the js/html not updating, even though it recieves the correct data.  I feel like the script.js is not removing the old data when someone logs in and is keeping it it memory or something along those lines.

I am not that great at js.

However, I am loving these scripts and if I can get this fixed then they will be getting used

**Comment by renzuzu** [comment]
open the js
and look for this line

![image](https://user-images.githubusercontent.com/82306584/206640298-c827bb12-6f04-4936-ae4a-8e241a3ce993.png)

this line deletes the content, so your problem should not be existing.

**Comment by PB-Developent** [comment]
Yes that's what I thought but for some reason it doesn't seem to be deleting it, which is why I am confused

**Comment by PB-Developent** [comment]
Latest I have found is that it seems to be holding data in the script, even though I am sending new data to it.

**Comment by PB-Developent** [comment]
I have actually managed to fix this issue

**Comment by renzuzu** [comment]
do a PR

**Comment by renzuzu** [comment]
great. i totally forgot to do a deepcopy or shallow copy , when doing adding data to local  Config.
not sure if this is a default behavior of lua

**Comment by PB-Developent** [comment]
Yeah it seems it vary. Sometimes I have gotten away with the way you had done it, other times I have had to do a copy of it for some reason.

I should of thought of this sooner before blaming the js, but then it just randomly hit me. It has definitely solved the spawn locations for me duplicating across characters.

Glad I could solve the issue, as I really like this and your multicharacter resource. And glad I could help contribute in some small way to hopefully prevent this issue for others.
