### ISSUE TITLE
[BUG] : some players sometimes die immediately when they first spawn 

### ISSUE THREAD

**Issue by unknownentity1337** [renzuzu/renzu_spawn#8]
Some players sometimes die immediately the first time they spawn, sometimes they still die even though they haven't spawned for the first time 
![image](https://user-images.githubusercontent.com/58675446/217963660-2e039d1d-361e-4293-a8f2-2360c5f6adcc.png)

**Comment by FrequencyRoleplay** [comment]
yeah its a qb core issue , i made him aware of it but he hasnt updated it yet. 

I get new players even flying in to city dead and it makes them end of leaving .  would love a fix for this asap

**Comment by renzuzu** [comment]
> 

what framework?
in ESX we never experience this.

there is some weird logic in qbcore resources that trigger death

show me some death logs too, so it will be easily to fixed this if this is a really bug.

there is only 2 things can cause this, dropping from sky before selecting character. (which is updated in mulitcharacter recently)

2 is when some resource trigger this.

**Comment by unknownentity1337** [comment]
the log says it fell from a height, I'm confused about how to fix it

**Comment by FrequencyRoleplay** [comment]
yes, character sometimes falling.

**Comment by FrequencyRoleplay** [comment]
I actually removed this spawn resource and the multicharcter still does the same thing alone.

**Comment by renzuzu** [comment]
> I actually removed this spawn resource and the multicharcter still does the same thing alone.

there is only 2 things can cause this, dropping from sky before selecting character. (which is fixed/updated in mulitcharacter recently) due some resource remove freezeentityposition to false

i have update the multicharacter few days ago.
sadly some resource setting freezeentityposition to false

![image](https://user-images.githubusercontent.com/82306584/218400798-c72691c9-6f2d-4511-b8b5-bc6e8d5e68f6.png)

the update already implemented, its on weather transition function.
do no remove the introcam function
