### ISSUE TITLE
Wants you to choose spawn, then character, then spawn.

### ISSUE THREAD

**Issue by SmityNfinity** [renzuzu/renzu_spawn#9]
I am sure this is a me issue. When we spawn in, it comes up before we can pick a character, and forces you to pick a location. then when we pick the location you can select your character, then you pick a location again, and it works.

**Comment by renzuzu** [comment]
its sounds, your spawnmanager are spawning your player forcibly.
possibly your framework are not set to use multicharacters.

what framework?
in ESX there is a config where you can config a multicharacter to true

**Comment by SmityNfinity** [comment]
Multicharacter is set and working. it is possibly the spawnmanager. I will look into it and get back to you. 

We are using ESX.

**Comment by SmityNfinity** [comment]
function forceRespawn()
    spawnLock = false
    respawnForced = true
end

is this where i would fix this issue in the script? changing forced to false?

**Comment by renzuzu** [comment]
i am not sure brother, 

use the latest spawnmanager from ESX repo is recommended.
and use latest esx too.
